apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../istio
patchesStrategicMerge:
  - config-map.yaml
images:
- name: gcr.io/arrikto/dexidp/dex
  newName: gcr.io/arrikto/dex
  newTag: 6a67e7c453a101a7ec3d07fde7b1d8f97b878cc8
